# Generated by Django 6.1.1 on 2026-09-28 18:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_games', models.PositiveIntegerField(default=0)),
                ('total_won_games', models.PositiveIntegerField(default=0)),
                ('total_lost_games', models.PositiveIntegerField(default=0)),
                ('total_digits', models.PositiveIntegerField(default=0)),
                ('challenge_total_games', models.PositiveIntegerField(default=0)),
                ('challenge_won_games', models.PositiveIntegerField(default=0)),
                ('challenge_lost_games', models.PositiveIntegerField(default=0)),
                ('challenge_personal_best', models.PositiveIntegerField(default=0)),
                ('challenge_total_digits', models.PositiveIntegerField(default=0)),
                ('hard_mode_total_games', models.PositiveIntegerField(default=0)),
                ('hard_mode_won_games', models.PositiveIntegerField(default=0)),
                ('hard_mode_lost_games', models.PositiveIntegerField(default=0)),
                ('hard_mode_personal_best', models.PositiveIntegerField(default=0)),
                ('hard_mode_total_digits', models.PositiveIntegerField(default=0)),
                ('day_playing_streak', models.PositiveIntegerField(default=0)),
                ('longest_playing_streak', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
