# Generated by Django 6.1.1 on 2026-09-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_emailverificationtoken_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='games_today',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_playing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
