# Generated by Django 6.1.1 on 2026-10-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_emailchangetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='last_sent_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='send_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
