# Generated by Django 6.1.1 on 2026-10-02 14:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_emailverificationtoken_last_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='send_window_started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
