# Generated by Django 6.1.1 on 2026-09-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengegame',
            name='end_digit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
