# Generated by Django 6.1.1 on 2026-09-29 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_alter_challengegame_end_digit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChallengeGame',
        ),
    ]
