# Generated by Django 6.1.1 on 2026-09-29 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenge', '0003_delete_challengegame'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BestTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_digit', models.PositiveIntegerField()),
                ('end_digit', models.PositiveIntegerField(blank=True, null=True)),
                ('hard_mode', models.BooleanField(default=False)),
                ('best_time_ms', models.PositiveBigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'start_digit', 'end_digit', 'hard_mode'), name='unique_best_time_range')],
            },
        ),
    ]
